spring.application.name=backend
server.port=8080

# --- CONEXIÓN A AZURE SQL ---
# Usamos ${DB_URL}, ${DB_USER} y ${DB_PASSWORD} para que lea
# los valores reales que configuraste en el portal de Azure.
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Dialecto para SQL Server
spring.jpa.database-platform=org.hibernate.dialect.SQLServer2012Dialect

# Configuración de JPA / Hibernate
# 'update' creará las tablas automáticamente si no existen
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Deshabilitar H2 completamente
spring.h2.console.enabled=false

# Data Initialization
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true